// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yentbjbdlipppplivjme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbnRiamJkbGlwcHBwbGl2am1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzA2MDMsImV4cCI6MjA3NDM0NjYwM30.iLDEt8QxSC5bsz6TwxcqY60ZQtmQlThEE7mSs6IVLfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});